# 1. 使用国内镜像源的基础镜像
FROM docker.m.daocloud.io/library/python:3.10-slim

# 2. 设置工作目录
WORKDIR /app

# 3. 设置系统时区为中国上海
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

# 4. 复制依赖文件并安装
COPY requirements.txt .
RUN pip install --no-cache-dir --default-timeout=1000 -r requirements.txt \
    -i https://pypi.tuna.tsinghua.edu.cn/simple

# 5. 【关键修改】复制 dags 目录下的所有内容（脚本、static 文件夹等）到当前工作目录 /app
# 这样 download_stations.py 和 static 文件夹都会在 /app 下
COPY dags/ .

# 6. 创建临时数据目录并设置权限
# 注意：此时 static 文件夹已经通过上面的 COPY 进来了，这里只是确保 tmp 存在
RUN mkdir -p /app/tmp && chmod 777 /app/tmp

# 7. 设置环境变量默认值
ENV TOS_ACCESS_KEY=""
ENV TOS_SECRET_KEY=""

# 8. 运行脚本 (此时脚本就在 /app 下)       
CMD ["python", "download_stations.py"]